# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = false # Disable warnings for cleaner test output
end

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[test rubocop]

desc "Run tests with coverage"
task :coverage do
  ENV["COVERAGE"] = "true"
  Rake::Task["test"].invoke
end

desc "Open an IRB session preloaded with this gem"
task :console do
  sh "irb -I lib -r ace/review"
end