source 'https://rubygems.org'

# Local workspace gems - flat in root (ace-* prefix)
gem 'ace-support-config', path: 'ace-support-config'
gem 'ace-context', path: 'ace-context'
gem 'ace-docs', path: 'ace-docs'
gem 'ace-git', path: 'ace-git'
gem 'ace-git-commit', path: 'ace-git-commit'
gem 'ace-git-secrets', path: 'ace-git-secrets'
gem 'ace-git-worktree', path: 'ace-git-worktree'
gem 'ace-lint', path: 'ace-lint'
gem 'ace-llm', path: 'ace-llm'
gem 'ace-support-models', path: 'ace-support-models'
gem 'ace-llm-providers-cli', path: 'ace-llm-providers-cli'
gem 'ace-support-nav', path: 'ace-support-nav'
gem 'ace-prompt', path: 'ace-prompt'
gem 'ace-review', path: 'ace-review'
gem 'ace-search', path: 'ace-search'
gem 'ace-support-core', path: 'ace-support-core'
gem 'ace-support-fs', path: 'ace-support-fs'
gem 'ace-support-mac-clipboard', path: 'ace-support-mac-clipboard'
gem 'ace-support-markdown', path: 'ace-support-markdown'
gem 'ace-support-timestamp', path: 'ace-support-timestamp'
gem 'ace-taskflow', path: 'ace-taskflow'
gem 'ace-test-runner', path: 'ace-test-runner'

# Shared dev/test tools for all gems
group :development, :test do
  gem 'ace-handbook', path: 'ace-handbook'
  gem 'ace-integration-claude', path: 'ace-integration-claude'
  gem 'ace-support-test-helpers', path: 'ace-support-test-helpers'
  gem 'bundler', '~> 2.4'
  gem 'minitest', '~> 5.20'
  gem 'minitest-reporters', '~> 1.6'
  gem 'rake', '~> 13.0'
  gem 'simplecov', '~> 0.22'
  gem 'webmock', '~> 3.19'
end
