#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/test/end_to_end_runner"
require "dry/cli"

begin
  Dry::CLI.new(Ace::Test::EndToEndRunner::CLI).call(arguments: ["suite"] + ARGV)
rescue Ace::Core::CLI::Error => e
  warn e.message
  exit(e.exit_code)
end
