#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/test/end_to_end_runner"

begin
  Ace::Test::EndToEndRunner::CLI.start(ARGV)
rescue Ace::Core::CLI::Error => e
  warn e.message
  exit(e.exit_code)
end
