# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

require "rubocop/rake_task"

RuboCop::RakeTask.new do |task|
  task.options = ["--display-cop-names", "--extra-details"]
end

task default: %i[test rubocop]

# Coverage task
require "simplecov"

task :coverage do
  ENV["COVERAGE"] = "true"
  Rake::Task[:test].invoke
end