#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/search"

# Start Thor CLI and exit with the returned status code
result = Ace::Search::CLI.start(ARGV)
exit(result.is_a?(Integer) ? result : 0)
