#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/compressor"

args = ARGV.empty? ? ["--help"] : ARGV

begin
  Ace::Compressor::CLI.start(args)
rescue Ace::Core::CLI::Error => e
  warn e.message
  exit(e.exit_code)
end
