#!/usr/bin/env ruby
# frozen_string_literal: true

require "ace/core"
require "ace/core/cli"

# Start FrameworkCLI (separate from Ace::Core::CLI module which is ace-support-cli infrastructure)
begin
  Ace::Core::FrameworkCLI.start(ARGV)
rescue Ace::Core::CLI::Error => e
  warn e.message
  exit(e.exit_code)
end
