# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-support-markdown.gemspec
gemspec

gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"
gem "ace-support-test-helpers", "~> 0.9", path: "../ace-support-test-helpers"
