# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-support-markdown.gemspec
gemspec

gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"
gem "ace-test-support", "~> 0.1", path: "../ace-test-support"
