#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "ace/core"
require "ace/test_runner"
require "ace/test_runner/suite"

options = {
  config: ".ace/test/suite.yml",
  parallel: nil,
  group: nil,
  verbose: false
}

parser = OptionParser.new do |opts|
  opts.banner = "Usage: ace-test-suite [options]"
  opts.separator ""
  opts.separator "Options:"

  opts.on("-c", "--config FILE", "Configuration file (default: .ace/test/suite.yml)") do |config|
    options[:config] = config
  end

  opts.on("-p", "--parallel N", Integer, "Maximum parallel processes") do |n|
    options[:parallel] = n
  end

  opts.on("-g", "--group GROUP", "Run only packages in specified group") do |group|
    options[:group] = group
  end

  opts.on("-v", "--verbose", "Show detailed output from tests") do
    options[:verbose] = true
  end

  opts.on("--no-color", "Disable colored output") do
    options[:no_color] = true
  end

  opts.on("-h", "--help", "Display this help") do
    puts opts
    exit 0
  end

  opts.on("--version", "Display version") do
    puts "ace-test-suite #{Ace::TestRunner::VERSION}"
    exit 0
  end

  opts.separator ""
  opts.separator "Examples:"
  opts.separator "  ace-test-suite                    # Run all configured packages"
  opts.separator "  ace-test-suite --parallel 16      # Run with 16 parallel processes"
  opts.separator "  ace-test-suite --group foundation # Run only foundation group"
  opts.separator "  ace-test-suite --verbose          # Show detailed test output"
  opts.separator ""
end

begin
  parser.parse!(ARGV)
rescue OptionParser::InvalidArgument => e
  puts "Error: #{e.message}"
  puts
  puts parser
  exit 1
end

# Load the config using namespace method
config = Ace::Core.get("test", file: "suite")

unless config
  puts "Error: Configuration file not found: .ace/test/suite.yml"
  puts
  puts "Create a test suite configuration at .ace/test/suite.yml in your project root"
  puts
  puts "Example configuration:"
  puts <<~YAML
    test_suite:
      max_parallel: 10
      packages:
        - name: ace-core
          path: ./ace-core
          group: foundation
          priority: 1
        - name: ace-test-runner
          path: ./ace-test-runner
          group: foundation
          priority: 1
      test_options:
        format: compact
        save_reports: true
  YAML
  exit 1
end

# Override config with command line options if provided
if options[:parallel]
  config["test_suite"]["max_parallel"] = options[:parallel]
end

if options[:group]
  config["test_suite"]["packages"].select! { |p| p["group"] == options[:group] }
  if config["test_suite"]["packages"].empty?
    puts "Error: No packages found in group '#{options[:group]}'"
    exit 1
  end
end

if options[:no_color]
  config["test_suite"]["display"] ||= {}
  config["test_suite"]["display"]["color"] = false
end

if options[:verbose]
  config["test_suite"]["test_options"] ||= {}
  config["test_suite"]["test_options"]["verbose"] = true
end

# Run the test suite with the config
begin
  exit_code = Ace::TestRunner::Suite.run(config)
  exit exit_code
rescue Ace::TestRunner::Suite::Error => e
  puts "Error: #{e.message}"
  exit 1
rescue Interrupt
  puts "\n\nTest suite execution interrupted"
  exit 130
rescue => e
  puts "Unexpected error: #{e.message}"
  puts e.backtrace if options[:verbose]
  exit 1
end