#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/docs"
require "ace/support/cli"

args = ARGV.empty? ? ["--help"] : ARGV

begin
  Ace::Support::Cli::Runner.new(Ace::Docs::CLI).call(args: args)
rescue Ace::Support::Cli::Error => e
  warn e.message
  exit(e.exit_code)
end
