#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/b36ts"
require "ace/support/cli"

args = ARGV.empty? ? ["--help"] : ARGV

begin
  Ace::Support::Cli::Runner.new(Ace::B36ts::CLI).call(args: args)
rescue Ace::Core::CLI::Error => e
  warn e.message
  exit(e.exit_code)
end
