# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-test-runner.gemspec
gemspec

# Local dependencies for development
gem "ace-core", path: "../ace-core"
gem "ace-test-support", path: "../ace-test-support"

group :development, :test do
  gem "rake", "~> 13.0"
  gem "minitest", "~> 5.0"
  gem "minitest-reporters", "~> 1.6"
end