# frozen_string_literal: true

require "bundler/setup"
require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
  t.verbose = true
end

desc "Run tests with verbose output"
task :test_verbose do
  ENV["VERBOSE"] = "true"
  Rake::Task["test"].invoke
end

task default: :test