# frozen_string_literal: true

require "bundler/gem_tasks"
require "minitest/test_task"

desc "Run tests using ace-test"
task :test do
  sh "ace-test"
end

desc "Run tests directly (CI mode)"
Minitest::TestTask.create(:ci)

task spec: :test
task default: :test
