# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

desc "Run tests using ace-test"
task :test do
  sh "ace-test"
end

desc "Run tests directly (CI mode)"
Rake::TestTask.new(:ci) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

task default: :test
