#!/usr/bin/env ruby
# bin/tr: Thin wrapper for recent-tasks utility

args = []
ARGV.each_with_index do |arg, idx|
  if arg == '--last' || arg == '-last'
    args << arg
    args << ARGV[idx+1] if ARGV[idx+1]
  end
end

exec(File.expand_path('../dev-handbook/tools/get-recent-tasks', __dir__), *args)
