#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "ace/overseer"

begin
  Ace::Overseer::CLI.start(ARGV)
rescue Interrupt
  exit(130)
rescue Ace::Core::CLI::Error => e
  warn e.message
  exit(e.exit_code)
end
