# frozen_string_literal: true

require_relative "base_formatter"

module Ace
  module TestRunner
    module Formatters
      # Markdown formatter for generating individual failure report files
      # This formatter is used internally for creating detailed failure reports
      # It is not exposed as a user-selectable output format
      class MarkdownFormatter < BaseFormatter
        def initialize(options = {})
          super
          @configuration = options
        end

        # Generate markdown report for a single failure
        def generate_failure_report(failure, index)
          lines = []

          lines << "# Failure Report: #{failure.test_name}"
          lines << ""
          lines << "**Generated:** #{Time.now.strftime('%Y-%m-%d %H:%M:%S')}"
          lines << "**Failure #:** #{index}"
          lines << ""
          lines << "## Summary"
          lines << ""
          lines << "- **Test:** `#{failure.full_test_name}`"
          lines << "- **Type:** #{failure.type.capitalize}"
          lines << "- **File:** `#{failure.file_path}`"
          lines << "- **Line:** #{failure.line_number}"
          lines << ""
          lines << "## Error Details"
          lines << ""
          lines << "### Message"
          lines << "```"
          lines << failure.message
          lines << "```"

          if failure.backtrace && !failure.backtrace.empty?
            lines << ""
            lines << "### Backtrace"
            lines << "```"
            lines << failure.backtrace.take(10).join("\n")
            lines << "```"
          end

          if failure.fix_suggestion
            lines << ""
            lines << "## Suggested Fix"
            lines << failure.fix_suggestion
          end

          lines << ""
          lines << "## Debugging Tips"
          lines << ""
          lines << "1. Check the assertion values - are they what you expected?"
          lines << "2. Review the test setup - is the test data correct?"
          lines << "3. Verify the implementation - does the code match the expected behavior?"
          lines << "4. Look for race conditions or timing issues if the test is flaky"
          lines << ""
          lines << "---"
          lines << "*Generated by ace-test-runner*"

          lines.join("\n")
        end

        # Not used for console output
        def format_stdout(result)
          ""
        end

        # Not used for report generation
        def format_report(report)
          {}
        end
      end
    end
  end
end