#!/usr/bin/env ruby

# Use absolute path resolution to support execution from any directory
lib_path = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift lib_path unless $LOAD_PATH.include?(lib_path)

require "coding_agent_tools/molecules/executable_wrapper"

CodingAgentTools::Molecules::ExecutableWrapper.new(
  command_path: ["code", "lint"],
  registration_method: :register_code_commands,
  executable_name: "code-lint"
).call
