#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "coding_agent_tools/molecules/alias_executable_wrapper"

CodingAgentTools::Molecules::AliasExecutableWrapper.new(
  alias_name: "csonet",
  executable_name: "csonet"
).call
