#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/coding_agent_tools"
require_relative "../lib/coding_agent_tools/cli/commands/git/status"

begin
  command = CodingAgentTools::Cli::Commands::Git::Status.new
  exit_code = command.call(**ARGV.each_with_object({}) { |arg, hash|
    if arg.start_with?("--")
      key_value = arg[2..-1].split("=", 2)
      key = key_value[0].tr("-", "_").to_sym
      value = key_value[1] || true
      hash[key] = value
    elsif arg.start_with?("-")
      # Handle short flags
      flag = arg[1..-1]
      case flag
      when "d"
        hash[:debug] = true
      when "s"
        hash[:short] = true
      when "v"
        hash[:verbose] = true
      when /^C(.+)/
        hash[:repository] = $1
      end
    end
  })
  exit(exit_code)
rescue => e
  warn "Error: #{e.message}"
  exit 1
end