#!/usr/bin/env ruby
# frozen_string_literal: true

# Use absolute path resolution to support execution from any directory
lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift lib_path unless $LOAD_PATH.include?(lib_path)

require 'coding_agent_tools/molecules/executable_wrapper'

CodingAgentTools::Molecules::ExecutableWrapper.new(
  command_path: ['git', 'fetch'],
  registration_method: :register_git_commands,
  executable_name: 'git-fetch'
).call
