#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "coding_agent_tools/molecules/executable_wrapper"

CodingAgentTools::Molecules::ExecutableWrapper.new(
  command_path: ["mistral", "query"],
  registration_method: :register_mistral_commands,
  executable_name: "llm-mistral-query"
).call
