#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "coding_agent_tools/molecules/executable_wrapper"

CodingAgentTools::Molecules::ExecutableWrapper.new(
  command_path: ["lms", "models"],
  registration_method: :register_lms_commands,
  executable_name: "llm-lmstudio-models"
).call
