#!/usr/bin/env ruby
# frozen_string_literal: true

# Nav Ls - Intelligent directory listing with path autocorrection
#
# This executable provides intelligent directory listing functionality
# with path autocorrection and enhanced formatting options.
#
# Usage: nav-ls [PATH] [OPTIONS]
#
# Examples:
#   nav-ls
#   nav-ls docs
#   nav-ls guides --long
#   nav-ls . --all
#   nav-ls tasks --long --all
#
# Options:
#   --long          Use long format (ls -l)
#   --all           Show hidden files (ls -a)
#   --autocorrect   Enable path autocorrection (default: true)
#   --no-autocorrect Disable path autocorrection

# Use absolute path resolution to support execution from any directory
lib_path = File.expand_path("../../lib", __FILE__)
$LOAD_PATH.unshift lib_path unless $LOAD_PATH.include?(lib_path)

require "coding_agent_tools/molecules/executable_wrapper"

CodingAgentTools::Molecules::ExecutableWrapper.new(
  command_path: ["nav", "ls"],
  registration_method: :register_nav_commands,
  executable_name: "nav-ls"
).call
