#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "ace/support/config"
require "ace/support/config/cli"

begin
  Ace::Support::Config::CLI.start(ARGV)
rescue SystemExit => e
  exit(e.status)
end
