#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "ace/nav"
require "ace/nav/cli"

# Run the CLI and exit with returned code
exit_code = Ace::Nav::Cli.new.run(ARGV)
exit(exit_code || 0)