# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-config.gemspec
gemspec

group :development do
  gem "minitest", "~> 5.0"
  gem "rake", "~> 13.0"
end
