#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/support/timestamp"

begin
  Ace::Support::Timestamp::CLI.start(ARGV)
rescue ArgumentError => e
  # Error message already printed by command
  warn e.backtrace.first(5).join("\n") if ENV["DEBUG"]
  exit 1
rescue StandardError => e
  # Error message already printed by command
  warn e.backtrace.first(5).join("\n") if ENV["DEBUG"]
  exit 1
end
