#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/support/timestamp"

begin
  result = Ace::Support::Timestamp::CLI.start(ARGV)
  exit(result.is_a?(Integer) ? result : 0)
rescue StandardError => e
  warn "Error: #{e.message}" if ENV["DEBUG"]
  exit 1
end
