# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-nav.gemspec
gemspec

# Use local ace-* gems in development
gem "ace-core", path: "../ace-core"
gem "ace-test-support", path: "../ace-test-support", group: [:development, :test]