# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-nav.gemspec
gemspec

# Use local ace-* gems in development
gem "ace-support-core", path: "../ace-support-core"
gem "ace-support-test-helpers", path: "../ace-support-test-helpers", group: [:development, :test]