# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ace-git-diff.gemspec
gemspec

# Development dependencies (local path for mono-repo development)
gem "ace-core", path: "../ace-core"
gem "ace-test-support", path: "../ace-test-support"

# Testing and development tools
gem "rake", "~> 13.0"
gem "minitest", "~> 5.0"
gem "minitest-reporters", "~> 1.6"
