# frozen_string_literal: true

require "test_helper"

class SynthesisIntegrationTest < AceReviewTest
  def setup
    super
    @session_dir = File.join(@test_dir, "session")
    FileUtils.mkdir_p(@session_dir)

    # Reset cached config before each test
    Ace::Review.reset_config!

    # Create test config with synthesis enabled
    create_test_config(<<~YAML)
      defaults:
        model: "test-model"
        preset: "test"
      synthesis:
        enabled: true
        default_model: "google:gemini-2.5-flash"
      presets:
        test:
          description: "Test preset"
          instructions:
            context:
              presets: ["project"]
          subject:
            context:
              sections:
                code:
                  title: "Code Changes"
                  files: ["test.rb"]
    YAML
  end

  def test_standalone_synthesis_command_execution
    # Create test reports
    report1 = File.join(@session_dir, "review-gemini-2-5-flash.md")
    report2 = File.join(@session_dir, "review-gpt-4.md")

    File.write(report1, sample_review_content("Gemini 2.5 Flash"))
    File.write(report2, sample_review_content("GPT-4"))

    # Mock LLM executor
    mock_llm_synthesis

    # Execute synthesis
    synthesizer = Ace::Review::Molecules::ReportSynthesizer.new
    result = synthesizer.synthesize(
      report_paths: [report1, report2],
      session_dir: @session_dir
    )

    # Verify result
    assert result[:success], "Synthesis should succeed"
    assert result[:output_file], "Should have output file"
    assert_equal File.join(@session_dir, "synthesis-report.md"), result[:output_file]

    # Verify file exists
    assert File.exist?(result[:output_file]), "Synthesis file should exist"

    # Verify content
    content = File.read(result[:output_file])
    assert_includes content, "Multi-Model Review Synthesis"
    assert_includes content, "gemini-2-5-flash, gpt-4"
  end

  def test_auto_synthesis_after_multi_model_execution
    # Create mock review output files that would be generated by multi-model executor
    model1_file = File.join(@session_dir, "review-gemini-2-5-flash.md")
    model2_file = File.join(@session_dir, "review-gpt-4.md")
    synthesis_file = File.join(@session_dir, "synthesis-report.md")

    File.write(model1_file, sample_review_content("Gemini 2.5 Flash"))
    File.write(model2_file, sample_review_content("GPT-4"))

    # Create manager with test config
    manager = Ace::Review::Organisms::ReviewManager.new(project_root: @test_dir)

    # Create options with multiple models and auto_execute enabled
    options = Ace::Review::Models::ReviewOptions.new(
      preset: "test",
      models: ["google:gemini-2.5-flash", "openai:gpt-4"],
      auto_execute: true
    )

    # Mock multi-model execution result
    multi_model_result = {
      success: true,
      results: {
        "google:gemini-2.5-flash" => {
          success: true,
          output_file: model1_file,
          model_slug: "gemini-2-5-flash"
        },
        "openai:gpt-4" => {
          success: true,
          output_file: model2_file,
          model_slug: "gpt-4"
        }
      },
      summary: {
        total_models: 2,
        success_count: 2,
        failure_count: 0
      }
    }

    # Track if synthesis was called
    synthesis_called = false
    synthesis_model_used = nil

    # Pre-generate mock response content (must be outside lambda)
    synthesis_content = mock_synthesis_response

    # Stub ReportSynthesizer to track calls and return mock result
    synthesizer_stub = ->(report_paths:, model: nil, session_dir: nil) {
      synthesis_called = true
      synthesis_model_used = model
      # Write synthesis output file
      File.write(synthesis_file, synthesis_content)
      {
        success: true,
        output_file: synthesis_file,
        models_synthesized: ["gemini-2-5-flash", "gpt-4"]
      }
    }

    # Stub MultiModelExecutor to return our mock result
    executor_stub = ->(**_args) { multi_model_result }

    # Create mock executor and synthesizer instances
    mock_executor = Ace::Review::Molecules::MultiModelExecutor.new
    mock_executor.define_singleton_method(:execute, executor_stub)

    mock_synthesizer = Ace::Review::Molecules::ReportSynthesizer.new
    mock_synthesizer.define_singleton_method(:synthesize, synthesizer_stub)

    # Test the internal methods directly
    # First verify should_synthesize? returns true for our setup
    assert manager.send(:should_synthesize?, multi_model_result, options),
           "should_synthesize? should return true for 2 successful reviews"

    # Now test auto_synthesize directly
    # We need to stub the synthesizer creation
    Ace::Review::Molecules::ReportSynthesizer.stub :new, mock_synthesizer do
      synthesis_result = manager.send(
        :auto_synthesize,
        multi_model_result,
        @session_dir,
        { preset: "test" },
        options
      )

      # Verify synthesis was called
      assert synthesis_called, "Synthesis should have been triggered"

      # Verify synthesis result
      assert synthesis_result[:success], "Synthesis should succeed"
      assert_equal synthesis_file, synthesis_result[:output_file]

      # Verify synthesis file was created
      assert File.exist?(synthesis_file), "Synthesis file should exist"

      # Verify synthesis content
      content = File.read(synthesis_file)
      assert_includes content, "Multi-Model Review Synthesis"
    end
  end

  def test_synthesis_skipped_when_disabled_via_flag
    # Create mock reviews
    report1 = File.join(@session_dir, "review-gemini.md")
    report2 = File.join(@session_dir, "review-gpt-4.md")

    File.write(report1, sample_review_content("Gemini"))
    File.write(report2, sample_review_content("GPT-4"))

    # Simulate ReviewManager synthesis check
    manager = Ace::Review::Organisms::ReviewManager.new(project_root: @test_dir)

    # Mock options with no_synthesize flag
    options = Ace::Review::Models::ReviewOptions.new(no_synthesize: true)

    # Mock result
    result = {
      success: true,
      results: {
        "gemini" => { success: true, output_file: report1 },
        "gpt-4" => { success: true, output_file: report2 }
      }
    }

    # should_synthesize? should return false
    should_run = manager.send(:should_synthesize?, result, options)
    refute should_run, "Synthesis should be skipped when no_synthesize flag is set"
  end

  def test_synthesis_skipped_when_disabled_via_config
    # Update config to disable synthesis
    create_test_config(<<~YAML)
      defaults:
        model: "test-model"
        preset: "test"
      synthesis:
        enabled: false
      presets:
        test:
          description: "Test preset"
          instructions:
            context:
              presets: ["project"]
          subject:
            context:
              sections:
                code:
                  title: "Code Changes"
                  files: ["test.rb"]
    YAML

    # Reset cached config to pick up new config file
    Ace::Review.reset_config!

    # Create mock reviews
    report1 = File.join(@session_dir, "review-gemini.md")
    report2 = File.join(@session_dir, "review-gpt-4.md")

    File.write(report1, sample_review_content("Gemini"))
    File.write(report2, sample_review_content("GPT-4"))

    # Simulate ReviewManager synthesis check
    manager = Ace::Review::Organisms::ReviewManager.new(project_root: @test_dir)

    # Mock result
    result = {
      success: true,
      results: {
        "gemini" => { success: true, output_file: report1 },
        "gpt-4" => { success: true, output_file: report2 }
      }
    }

    # should_synthesize? should return false
    should_run = manager.send(:should_synthesize?, result, nil)
    refute should_run, "Synthesis should be skipped when disabled in config"
  end

  def test_synthesis_skipped_with_less_than_two_successful_reviews
    # Create mock reviews (only one succeeds)
    report1 = File.join(@session_dir, "review-gemini.md")
    File.write(report1, sample_review_content("Gemini"))

    manager = Ace::Review::Organisms::ReviewManager.new(project_root: @test_dir)

    # Mock result with only one success
    result = {
      success: true,
      results: {
        "gemini" => { success: true, output_file: report1 },
        "gpt-4" => { success: false, error: "Model error" }
      }
    }

    # should_synthesize? should return false
    should_run = manager.send(:should_synthesize?, result, nil)
    refute should_run, "Synthesis should be skipped with less than 2 successful reviews"
  end

  def test_synthesis_uses_custom_model
    # Create test reports
    report1 = File.join(@session_dir, "review-gemini.md")
    report2 = File.join(@session_dir, "review-gpt-4.md")

    File.write(report1, sample_review_content("Gemini"))
    File.write(report2, sample_review_content("GPT-4"))

    # Track which model was used for synthesis
    synthesis_model_used = nil

    # Create synthesizer with stubbed executor
    synthesizer = Ace::Review::Molecules::ReportSynthesizer.new
    synthesizer.llm_executor.define_singleton_method(:execute) do |**args|
      synthesis_model_used = args[:model]
      {
        success: true,
        response: mock_synthesis_response,
        metadata: {}
      }
    end

    # Execute with custom synthesis model
    synthesizer.synthesize(
      report_paths: [report1, report2],
      model: "anthropic:claude-sonnet-4",
      session_dir: @session_dir
    )

    # Verify custom model was used
    assert_equal "anthropic:claude-sonnet-4", synthesis_model_used
  end

  private

  def sample_review_content(model_name)
    <<~MARKDOWN
      # Code Review by #{model_name}

      ## Summary
      Reviewed code changes for potential issues.

      ## Critical Issues
      1. Missing error handling in line 45
      2. Potential null pointer exception in line 67

      ## Recommendations
      - Add input validation
      - Improve test coverage
      - Document complex algorithms

      ## Positive Aspects
      - Good code structure
      - Clear variable naming
    MARKDOWN
  end

  def mock_synthesis_response
    <<~MARKDOWN
      # Multi-Model Review Synthesis

      ## Overview
      - Models: gemini, gpt-4

      ## Consensus Findings (All Models Agree)
      1. Missing error handling in line 45
      2. Need better test coverage

      ## Strong Recommendations (2+ Models)
      1. Add input validation
      2. Document complex algorithms

      ## Unique Insights
      ### From gemini:
      - Performance optimization opportunity in loop

      ### From gpt-4:
      - Consider using Result pattern for error handling

      ## Conflicting Views & Resolution
      No significant conflicts identified

      ## Prioritized Action Items
      1. Fix missing error handling (high priority - consensus)
      2. Add input validation (medium priority)
      3. Improve test coverage (medium priority)
      4. Document complex algorithms (low priority)
    MARKDOWN
  end

  def mock_llm_synthesis
    # Stub LLM executor globally for all ReportSynthesizer instances
    Ace::Review::Molecules::LlmExecutor.class_eval do
      alias_method :original_execute, :execute

      def execute(**_args)
        {
          success: true,
          response: mock_synthesis_response_global,
          metadata: { tokens: 1000 }
        }
      end

      def mock_synthesis_response_global
        <<~MARKDOWN
          # Multi-Model Review Synthesis

          ## Overview
          - Models: gemini-2-5-flash, gpt-4

          ## Consensus Findings (All Models Agree)
          1. Missing error handling

          ## Prioritized Action Items
          1. Fix error handling
        MARKDOWN
      end
    end
  end
end
