#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/ace/git/secrets"

# Start Thor CLI and exit with the returned status code
result = Ace::Git::Secrets::CLI.start(ARGV)
exit(result.is_a?(Integer) ? result : 0)
